# Synthetix SubGraph auto-deployer

# Deploys new synthetix subgraph when new versions are tagged and pushed
# (via `git push --follow-tags` for example)

env_defaults: &env_defaults
  working_directory: ~
  docker:
    - image: circleci/node:10.16

version: 2
jobs:
  prepare:
    <<: *env_defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1.0-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1.0-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1.0-dependencies-{{ checksum "package-lock.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  deploy:
    <<: *env_defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run codegen:snx # TODO: should kick-off codegen:snx when snx files changed, same with codegen:rates
      - run:
          name: Deploy with auth
          command: |
            # TODO: as above, should be deploy:snx or deploy:rates depending on changes in commit
            npm run deploy:snx > /dev/null # output to dev/null to not show access code in logs
            # Note: does not exit non-zero on failure, waiting for https://github.com/graphprotocol/graph-cli/issues/351"

workflows:
  version: 2

  deploy-on-new-version:
    jobs:
      - prepare:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - prepare
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
